package ar.edu.unsam.consorciovirtual.domain;

public enum Rubro {
    SUELDOYCARGASSOCIALES,
    SERVICIOSPUBICOS,
    OTROSSERVICIOS,
    MANTENIMIENTOPARTESCOMUNES,
    RESPARACIONESENUNIDADES,
    GASTOSBANCARIOS,
    LIMPIEZA,
    ADMINISTRACION,
    SEGUROS,
    OTROS
}
