version: "3.7"


services:
  #MYSQL --------------------------------
  mysql-server:
    container_name: mysql-container
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - 3307:3306 
    environment:
        MYSQL_DATABASE: 'consorcio_virtual'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true' 